### ISSUE TITLE
安装报错了

### ISSUE THREAD

**Issue by jasonqiao36** [laike9m/Cyberbrain#3]
pip install cyberbrain报错:
```
Traceback (most recent call last):
  File "demo3.py", line 20, in <module>
    import cyberbrain
  File "/home/jason/.venv/cyberbrain_env/lib/python3.7/site-packages/cyberbrain/__init__.py", line 1, in <module>
    from .api import init, register
  File "/home/jason/.venv/cyberbrain_env/lib/python3.7/site-packages/cyberbrain/api.py", line 8, in <module>
    from . import backtrace, flow, format, testing, utils
  File "/home/jason/.venv/cyberbrain_env/lib/python3.7/site-packages/cyberbrain/backtrace.py", line 6, in <module>
    from . import utils
  File "/home/jason/.venv/cyberbrain_env/lib/python3.7/site-packages/cyberbrain/utils.py", line 13, in <module>
    import black
ModuleNotFoundError: No module named 'black'
```
需要把black加入到正式的依赖中

**Comment by laike9m** [comment]
我的问题。。
